import json, sys

letters = 0, 11, 8, 2, 14, 3, 5, 4, 34, 38, 40, 37, 46, 45, 31, 35, 12, 15, 1, 17, 32, 9, 13, 7, 16, 6
nums = 29, 18, 19, 20, 21, 23, 22, 26, 28, 25

keys = dict(
	space=49,
	enter=36,
	control=59, option=58, command=55,
	up=126,
	down=125,
	left=123,
	right=124,
	shift=56,
	capslock=57,
	tab=48,
	backtick=50,
	comma=43, period=47, slash=44, backslash=42,
	delete=51,
	escape=53,
)

buttons = 'dpadUp dpadLeft dpadRight dpadDown X O square triangle PS touchpad options share L1 L2 L3 R1 R2 R3'.split(' ')

axes = 'leftX- leftX+ leftY- leftY+ rightX- rightX+ rightY- rightY+'.split(' ')

for i, x in enumerate(letters):
	keys[chr(ord('a') + i)] = x
for i, x in enumerate(nums):
	keys[str(i)] = x

def parse(data):
	lines = (line.split('#', 1)[0].strip() for line in data.split('\n'))
	return dict(map(str.strip, line.split('=', 1)) for line in lines if line)

# Inputs this mapping claims. Remote Play now installs its own keyboard mapping
# as an NSEvent local monitor, so iohid_wrap.m has to know exactly which inputs
# to withhold from it -- anything else must still reach the app.
mappedKeys = []
mapLeftMouse = False
mapRightMouse = False

with open('mapKeys.h', 'w') as fp:
	keysticks = []
	mouseLook = None
	for k, v in parse(open(sys.argv[1]).read()).items():
		if k in keys or k == 'leftMouse' or k == 'rightMouse':
			src = k
			if k in keys:
				k = 'DOWN(%i)' % keys[src]
			if v in buttons:
				print('%s = %s;' % (v, k), file=fp)
			elif v in axes:
				stick = v[:-2]
				if stick not in keysticks:
					print('%sX = %sY = 0;' % (stick, stick), file=fp)
					keysticks.append(stick)
				print('if(%s) %s %s= 1;' % (k, v[:-1], v[-1]), file=fp)
			else:
				print('Unknown button:', v)
				continue
			if src in keys:
				mappedKeys.append(keys[src])
			elif src == 'leftMouse':
				mapLeftMouse = True
			else:
				mapRightMouse = True
		elif k.startswith('mouseLook.'):
			if mouseLook is None:
				mouseLook = dict(type='linear', deadZone='.1', decay='10', multX='1', multY='1',
					sensitivity='.15', drain='400', maxGlide='.1', captureKey='escape', captureMode='lock', stick='right',
					mode='stick', gyroSensitivity='30', gyroYawOffset='15', gyroPitchOffset='13',
					gyroYawSign='1', gyroPitchSign='1', gyroTimestampStep='750')
			mouseLook[k.split('.', 1)[1]] = v
		else:
			print('Unknown key:', k)

	if mouseLook is not None and mouseLook.get('mode', 'stick') != 'gyro':
		if mouseLook['type'] == 'linear':
			print(\
'''{stick}X = fmax(-1.f, fmin(1.f, mouseDeltaX * (float) ({sensitivity}) * (float) ({multX})));
{stick}Y = fmax(-1.f, fmin(1.f, mouseDeltaY * (float) ({sensitivity}) * (float) ({multY})));
if(fabs({stick}X) > {deadZone} || fabs({stick}Y) > {deadZone})
	[self decayKick];
else {{
	{stick}X = {stick}Y = 0;
	mouseDeltaX = mouseDeltaY = 0;
}}'''.format(**mouseLook), file=fp)
		else:
			print('Unknown mouseLook type:', mouseLook)
			mouseLook = None

with open('mapMeta.h', 'w') as fp:
	print('/* Generated by shockemu.py from %s -- do not edit. */' % sys.argv[1], file=fp)
	uniq = sorted(set(mappedKeys))
	print('#define SE_NUM_MAPPED_KEYS %i' % len(uniq), file=fp)
	# A zero-length array is not valid C, so always emit at least one element.
	print('static const unsigned short se_mappedKeys[] = {%s};'
		% ', '.join(str(x) for x in (uniq or [0])), file=fp)
	print('#define SE_MAP_LEFT_MOUSE %i' % (1 if mapLeftMouse else 0), file=fp)
	print('#define SE_MAP_RIGHT_MOUSE %i' % (1 if mapRightMouse else 0), file=fp)
	print('#define SE_MAP_MOUSELOOK %i' % (0 if mouseLook is None else 1), file=fp)
	capture = (mouseLook or {}).get('captureKey', 'escape')
	if capture not in keys:
		print('Unknown mouseLook.captureKey:', capture)
		capture = 'escape'
	print('#define SE_CAPTURE_KEY %i /* %s */' % (keys[capture], capture), file=fp)
	mode = (mouseLook or {}).get('captureMode', 'lock')
	if mode not in ('lock', 'recenter'):
		print('Unknown mouseLook.captureMode:', mode)
		mode = 'lock'
	print('#define SE_CAPTURE_MODE_LOCK %i /* %s */' % (1 if mode == 'lock' else 0, mode), file=fp)
	# Modifiers arrive as flagsChanged; map the keycode to its NSEvent flag.
	modifiers = {56: 'NSEventModifierFlagShift', 59: 'NSEventModifierFlagControl',
		58: 'NSEventModifierFlagOption', 55: 'NSEventModifierFlagCommand',
		57: 'NSEventModifierFlagCapsLock'}
	print('#define SE_CAPTURE_MODIFIER %s' % modifiers.get(keys[capture], '0'), file=fp)
	print('#define SE_MOUSE_SENSITIVITY %s' % (mouseLook or {}).get('sensitivity', '.15'), file=fp)
	print('#define SE_MOUSE_DRAIN %s' % (mouseLook or {}).get('drain', '400'), file=fp)
	print('#define SE_MOUSE_MAXGLIDE %s' % (mouseLook or {}).get('maxGlide', '.1'), file=fp)
	ml = mouseLook or {}
	gyro = ml.get('mode', 'stick') == 'gyro'
	print('#define SE_MOUSE_MODE_GYRO %i' % (1 if gyro else 0), file=fp)
	print('#define SE_GYRO_SENS %s' % ml.get('gyroSensitivity', '30'), file=fp)
	print('#define SE_GYRO_YAW_OFF %s' % ml.get('gyroYawOffset', '15'), file=fp)
	print('#define SE_GYRO_PITCH_OFF %s' % ml.get('gyroPitchOffset', '13'), file=fp)
	print('#define SE_GYRO_YAW_SIGN %s' % ml.get('gyroYawSign', '1'), file=fp)
	print('#define SE_GYRO_PITCH_SIGN %s' % ml.get('gyroPitchSign', '1'), file=fp)
	print('#define SE_GYRO_TS_STEP %s' % ml.get('gyroTimestampStep', '750'), file=fp)

print('Mapped %i key(s); leftMouse=%s rightMouse=%s mouseLook=%s'
	% (len(set(mappedKeys)), mapLeftMouse, mapRightMouse, mouseLook is not None))
